NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.cbseorg.nic.in-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.cbseorg.nic.in-cert.pem
    OrganizationalUnitIdentifier: peer
