version: '2'

volumes:
  nic.in:
  peer0.cbseorg.nic.in:
  peer0.schooloneorg.school.nic.in:
  peer0.schooltwoorg.school.nic.in:

networks:
  schools:
services:
  cbse-ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cbseorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cbseorg.nic.in-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4ef4f6768ed152d08c555af47a07cb7378c51b0846690b3887da4e4c7429c0bf_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.cbseorg.nic.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4ef4f6768ed152d08c555af47a07cb7378c51b0846690b3887da4e4c7429c0bf_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/cbseorg.nic.in/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCBSEOrg
    networks:
      - schools

  schoolone-ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-schooloneorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.schooloneorg.school.nic.in-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3d1aaf89769cd33164bc7dfdd85fa01dfe57639178a29db24c3325ce6ee9d61e_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.schooloneorg.school.nic.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/3d1aaf89769cd33164bc7dfdd85fa01dfe57639178a29db24c3325ce6ee9d61e_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/schooloneorg.school.nic.in/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSchoolOneOrg
    networks:
      - schools
  
  schooltwo-ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-schooltwoorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.schooltwoorg.school.nic.in-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/46ff4d0590cfa9fe44c814633b24c8c8bf8125f23c6435ae181e7cb9163266f4_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.schooltwoorg.school.nic.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/46ff4d0590cfa9fe44c814633b24c8c8bf8125f23c6435ae181e7cb9163266f4_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/schooltwoorg.school.nic.in/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSchoolTwooOrg
    networks:
      - schools
  
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.cbseorg.nic.in:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/cbseorg.nic.in/users/Admin@cbseorg.nic.in/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/
    networks:
        - schools

  orderer.nic.in:
    extends:
      file:   docker-compose-base.yaml
      service: orderer.nic.in
    container_name: orderer.nic.in
    networks:
      - schools

  couchdb0:
    extends:
      file:   docker-compose-base.yaml
      service: couchdb0
    container_name: couchdb0
    networks:
      - schools

  peer0.cbseorg.nic.in:
    extends:
      file:   docker-compose-base.yaml
      service: peer0.cbseorg.nic.in
    container_name: peer0.cbseorg.nic.in
    networks:
      - schools
  
  couchdb1:
    extends:
      file:   docker-compose-base.yaml
      service: couchdb1
    container_name: couchdb1
    networks:
      - schools

  peer0.schooloneorg.school.nic.in:
    extends:
      file:   docker-compose-base.yaml
      service: peer0.schooloneorg.school.nic.in
    container_name: peer0.schooloneorg.school.nic.in
    networks:
      - schools

  couchdb2:
    extends:
      file:   docker-compose-base.yaml
      service: couchdb2
    container_name: couchdb0
    networks:
      - schools

  peer0.schooltwoorg.school.nic.in:
    extends:
      file:   docker-compose-base.yaml
      service: peer0.schooltwoorg.school.nic.in
    container_name: peer0.schooltwoorg.school.nic.in
    networks:
      - schools