version: '2'

networks:
  schools:

volumes:
  nic.in:
  peer0.cbseorg.nic.in:
  peer0.schooloneorg.school.nic.in:
  peer0.schooltwoorg.school.nic.in:
  
services:
  cbse-ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cbseorg
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.cbseorg.nic.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/684b54dccef67f5d52054c5d0532870c1fb5090a204fb8e14bd4ba303f8c279e_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/cbseorg.nic.in/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCBSEOrg
    networks:
      - schools

  schoolone-ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-schooloneorg
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.schooloneorg.school.nic.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a60a934833e70103a525f37b6b8ce504b113c68ae1234cde231205dd3a631b2a_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/schooloneorg.school.nic.in/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSchoolOneOrg
    networks:
      - schools
  
  schooltwo-ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-schooltwoorg
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.schooltwoorg.school.nic.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/44e0a31ca29dcd147cb56581ac8f1fb0490622d7b96f3112a0fed8cce3cc30c2_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/schooltwoorg.school.nic.in/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSchoolTwooOrg
    networks:
      - schools
  
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_ID=peer0.cbseorg.nic.in
      - CORE_PEER_ADDRESS=peer0.cbseorg.nic.in:7051
      - CORE_PEER_LOCALMSPID=CBSEOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/chaincode
    # command: /bin/bash -c '/opt/channel-artifacts/setup.sh'
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH:/opt/gopath
        - ./crypto-config/peerOrganizations/cbseorg.nic.in/users/Admin@cbseorg.nic.in/msp:/etc/hyperledger/msp
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - .:/opt/channel-artifacts
    networks:
        - schools

  cli2:
    container_name: cli2
    image: hyperledger/fabric-tools:latest
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_ID=peer0.schooloneorg.school.nic.in
      - CORE_PEER_ADDRESS=peer0.schooloneorg.school.nic.in:7051
      - CORE_PEER_LOCALMSPID=SchoolOneOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/chaincode
    # command: /bin/bash -c '/opt/channel-artifacts/setup.sh'
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH:/opt/gopath
        - ./crypto-config/peerOrganizations/schooloneorg.school.nic.in/users/Admin@schooloneorg.school.nic.in/msp:/etc/hyperledger/msp
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - .:/opt/channel-artifacts
    networks:
        - schools

  # chaincode:
  #   container_name: chaincode
  #   image: hyperledger/fabric-ccenv
  #   tty: true
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - FABRIC_LOGGING_SPEC=debug
  #     - CORE_PEER_ID=peer0.cbseorg.nic.in
  #     - CORE_PEER_ADDRESS=peer0.cbseorg.nic.in:7051
  #     - CORE_PEER_LOCALMSPID=CBSEOrg
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
  #     - CORE_CHAINCODE_KEEPALIVE=10
  #   working_dir: /opt/gopath/src/github.com/chaincode
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - $GOPATH:/opt/gopath
  #       - ./crypto-config/peerOrganizations/cbseorg.nic.in/peers/peer0.cbseorg.nic.in/msp:/etc/hyperledger/msp
  #       - ../chaincode/:/opt/gopath/src/github.com/chaincode
  #   networks:
  #       - schools
  #   depends_on:
  #       - orderer.nic.in
  #       - peer0.cbseorg.nic.in


  orderer.nic.in:
    extends:
      file:   docker-compose-base.yaml
      service: orderer.nic.in
    container_name: orderer.nic.in
    networks:
      - schools

  couchdb0:
    extends:
      file:   docker-compose-base.yaml
      service: couchdb0
    container_name: couchdb0
    networks:
      - schools

  peer0.cbseorg.nic.in:
    extends:
      file:   docker-compose-base.yaml
      service: peer0.cbseorg.nic.in
    container_name: peer0.cbseorg.nic.in
    networks:
      - schools
  
  couchdb1:
    extends:
      file:   docker-compose-base.yaml
      service: couchdb1
    container_name: couchdb1
    networks:
      - schools

  peer0.schooloneorg.school.nic.in:
    extends:
      file:   docker-compose-base.yaml
      service: peer0.schooloneorg.school.nic.in
    container_name: peer0.schooloneorg.school.nic.in
    networks:
      - schools

  couchdb2:
    extends:
      file:   docker-compose-base.yaml
      service: couchdb2
    container_name: couchdb2
    networks:
      - schools

  peer0.schooltwoorg.school.nic.in:
    extends:
      file:   docker-compose-base.yaml
      service: peer0.schooltwoorg.school.nic.in
    container_name: peer0.schooltwoorg.school.nic.in
    networks:
      - schools
